// Before using this header you MUST define INSTRUCTION_(a, b) macro

//            Name  Argument
//                   count
INSTRUCTION_(  HLT,    0)

INSTRUCTION_(  PUSH,   1)
INSTRUCTION_(  DUB,    0)
// TODO POP VOID

INSTRUCTION_(  IN,     0)
INSTRUCTION_(  OUT,    0)

INSTRUCTION_(  ADD,    0)
INSTRUCTION_(  SUB,    0)
INSTRUCTION_(  MUL,    0)
INSTRUCTION_(  DIV,    0)
INSTRUCTION_(  SQRT,   0)

INSTRUCTION_(  PUSHR,  1)
INSTRUCTION_(  POPR,   1)

INSTRUCTION_(  PUSHM,  1)
INSTRUCTION_(  POPM,   1)

INSTRUCTION_(  PUSHV,  1)
INSTRUCTION_(  POPV,   1)

INSTRUCTION_(  JMP,    1)

INSTRUCTION_(  JB,     1)
INSTRUCTION_(  JBE,    1)
INSTRUCTION_(  JA,     1)
INSTRUCTION_(  JAE,    1)
INSTRUCTION_(  JE,     1)
INSTRUCTION_(  JNE,    1)

INSTRUCTION_(  CALL,   1)
INSTRUCTION_(  RET,    0)

INSTRUCTION_(  DRAW,   0)

INSTRUCTION_(  SIN,    0)

#undef INSTRUCTION_
